const data = {
  products: [
    {
      name: "Nike",
      slug: "nike slom",
      categorie: "shirts",
      image: "/images/p1.jpg",
      prices: 120,
      quntStock: 0,
      brand: "nike",
      rating: 3.5,
      numReview: 10,
      descrption: "hight quality",
    },
    {
      name: "addidas",
      slug: "adidaas slim",
      categorie: "shirts",
      image: "/images/p2.jpg",
      prices: 320,
      quntStock: 14,
      brand: "addida",
      rating: 4.5,
      numReview: 10,
      descrption: "hight quality",
    },
    {
      name: "addidas fit pant",
      slug: "adidas slim",
      categorie: "fit pnat",
      image: "/images/p3.jpg",
      prices: 220,
      quntStock: 10,
      brand: "addida fit",
      rating: 1.5,
      numReview: 7,
      descrption: "hight quality",
    },
    {
      name: "nike fit",
      slug: "fit slim",
      categorie: "fit pant",
      image: "/images/p4.jpg",
      prices: 140,
      quntStock: 70,
      brand: "nike fit",
      rating: 1.5,
      numReview: 8,
      descrption: "hight quality",
    },
  ],
};

export default data;
